name = "mada-chatgpt"
main = "src/index.js"
compatibility_date = "2023-03-03"
usage_model = "bundled"
env = { }
kv_namespaces = [
  { binding = "kv", id = "0eae6db52f624209b64086e989eaad62" }
]

[triggers]
crons = [ ]
